export const PREFIX = 'QUESTION';

export const FETCH_QUESTION_REQUEST = `${PREFIX}//FETCH_QUESTION_REQUEST`;
export const FETCH_QUESTION_COMPLETED = `${PREFIX}//FETCH_QUESTION_COMPLETED`;
export const FETCH_QUESTION_FAILURE = `${PREFIX}//FETCH_QUESTION_FAILURE`;
