export const PREFIX = 'QUESTION';

export const FETCH_QUESTION_REQUEST = `${PREFIX}//FETCH_QUESTION_REQUEST`;
export const FETCH_QUESTION_SUCCESS = `${PREFIX}//FETCH_QUESTION_SUCCESS`;
export const FETCH_QUESTION_FAILURE = `${PREFIX}//FETCH_QUESTION_FAILURE`;

export const SET_LIKED = `$${PREFIX}//SET_LIKED`;
export const SET_DISLIKED = `$${PREFIX}//SET_DISLIKED`;
